name: Mommy + Man
favicon: null
layout_spectrum: 0.7826794860884547
typography_spectrum: 0.7414349548052996
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.10015256446786225
  lightness: 0.790070123039186
  saturation: 0.9820834940765053
  rhythmicContrast: 0.9560941876843572
purpose: []
